// Try Catch
const num1 = 5;
const num3 = 10;

try {
    console.log(num1 + num2);
} catch (error) {
    console.log(error);
}